spring:
  profiles:
    active: dev
  application:
    name: workflow-service
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: com.kylas.sales.workflow.sql.PostgreSqlDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/workflow
    username: postgres
    password: password
  rabbitmq:
    host: localhost
    username: test
    password: test
    virtual-host: sling-sales
    listener:
      simple:
        prefetch: 1
  flyway:
    enabled: false
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat

security:
  jwt:
    key: test
  crypto:
    key: secret

server:
  port: 9002
  max-http-header-size: 10KB

management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

client:
  iam:
    basePath: http://localhost:8081
  config:
    basePath: http://localhost:8086
  search:
    basePath: http://localhost:8083
  product:
    basePath: http://localhost:8089