spring:
  profiles:
    active: dev
  application:
    name: workflow-service
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: com.kylas.sales.workflow.sql.PostgreSqlDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/workflow
    username: postgres
    password: password
  flyway:
    enabled: false
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat

security:
  jwt:
    key: test
