package com.kylas.sales.workflow.domain.workflow.action.email;

public enum EmailActionType {
  RECORD_OWNER,
  RECORD_CREATED_BY,
  RECORD_UPDATED_BY,
  RECORD_PRIMARY_EMAIL,
  WORKFLOW_CREATOR,
  WORKFLOW_UPDATER,
  ALL_AVAILABLE_EMAILS,
  ALL_ASSOCIATED_CONTACTS,
  TENANT_EMAIL,
  CUSTOM_EMAIL,
  USER,
  LEAD,
  CONTACT

}
